### ISSUE TITLE
Bevymark and some other examples seem to fail on website

### ISSUE THREAD

**Issue by laundmo** [bevyengine/bevy-website#844]
Both on firefox and chrome-based browsers, both the webgl and webgpu builds of bevymark on the website seem to error out with a unreachable error.
```
Uncaught (in promise) RuntimeError: unreachable executed
    __wbg_finalize_init https://bevy-webgl2-examples.pages.dev/Stress Tests/many-foxes/wasm_example.js:1901
    __wbg_init https://bevy-webgl2-examples.pages.dev/Stress Tests/many-foxes/wasm_example.js:1937
```

this is the error from firefox using webgl. the chrome one has a few more addresses in the traceback, but is essentially the same.

the same happens for some other examples

**Comment by thebluefish** [comment]
I am experiencing the same issue on Windows 10, running [the bevymark example](https://bevyengine.org/examples/Stress%20Tests/bevymark/), I get different errors depending on browser.

Chrome:
> Uncaught (in promise) RuntimeError: unreachable
    at 04f0e2a2:0x1008f6c
    at 04f0e2a2:0x1f6543
    at 04f0e2a2:0xf730bf
    at 04f0e2a2:0xf70863
    at 04f0e2a2:0xfeaa5c
    at __wbg_finalize_init (wasm_example.js:1901:10)
    at __wbg_init (wasm_example.js:1937:12)

Firefox:
> Uncaught (in promise) RuntimeError: unreachable executed
    __wbg_finalize_init https://bevy-webgl2-examples.pages.dev/Stress Tests/bevymark/wasm_example.js:1901
    __wbg_init https://bevy-webgl2-examples.pages.dev/Stress Tests/bevymark/wasm_example.js:1937

I found a thread on November 15 indicating that I ran the same example fine at that time, suggesting the problem was introduced with the 0.12.1 release.

**Comment by laundmo** [comment]
I'm pretty sure these are the same error, just represented differently

**Comment by BD103** [comment]
Could you both try running Bevymark again, now that 0.13 is released? I'm not able to reproduce the issue, so I'm wondering if it was patched.
